# Mapping of RAWG platform slugs to their documented numeric identifiers.
PLATFORM_SLUG_TO_ID: dict[str, int] = {
    "xbox-one": 1,
    "ios": 3,
    "pc": 4,
    "macos": 5,
    "linux": 6,
    "nintendo-switch": 7,
    "nintendo-3ds": 8,
    "nintendo-ds": 9,
    "wii-u": 10,
    "wii": 11,
    "neogeo": 12,
    "nintendo-dsi": 13,
    "xbox360": 14,
    "playstation2": 15,
    "playstation3": 16,
    "psp": 17,
    "playstation4": 18,
    "ps-vita": 19,
    "android": 21,
    "atari-flashback": 22,
    "atari-2600": 23,
    "game-boy-advance": 24,
    "atari-8-bit": 25,
    "game-boy": 26,
    "playstation1": 27,
    "atari-7800": 28,
    "atari-5200": 31,
    "atari-st": 34,
    "apple-ii": 41,
    "game-boy-color": 43,
    "atari-lynx": 46,
    "nes": 49,
    "atari-xegs": 50,
    "macintosh": 55,
    "snes": 79,
    "xbox-old": 80,
    "nintendo-64": 83,
    "gamecube": 105,
    "dreamcast": 106,
    "sega-saturn": 107,
    "3do": 111,
    "jaguar": 112,
    "sega-32x": 117,
    "sega-cd": 119,
    "sega-master-system": 74,
    "game-gear": 77,
    "commodore-amiga": 166,
    "genesis": 167,
    "web": 171,
    "xbox-series-x": 186,
    "playstation5": 187,
}

PARENT_PLATFORM_SLUG_TO_ID: dict[str, int] = {
    "pc": 1,
    "playstation": 2,
    "xbox": 3,
    "ios": 4,
    "mac": 5,
    "linux": 6,
    "nintendo": 7,
    "android": 8,
    "atari": 9,
    "commodore-amiga": 10,
    "sega": 11,
    "3do": 12,
    "neo-geo": 13,
    "web": 14,
}

STORE_SLUG_TO_ID: dict[str, int] = {
    "steam": 1,
    "xbox-store": 2,
    "playstation-store": 3,
    "apple-appstore": 4,
    "gog": 5,
    "nintendo": 6,
    "xbox360": 7,
    "google-play": 8,
    "itch": 9,
    "epic-games": 11,
}

DEVELOPER_SLUGS: list[str] = [
    "valve-software",
    "ubisoft",
    "feral-interactive",
    "ubisoft-montreal",
    "square-enix",
    "capcom",
    "electronic-arts",
    "aspyr-media",
    "sony-interactive-entertainment",
    "sega",
    "bethesda-softworks",
    "telltale-games",
    "2k",
    "warner-bros-interactive",
    "bandai-namco-entertainment-america-inc",
    "id-software",
    "gearbox-software",
    "devolver-digital",
    "bethesda-game-studios",
    "nvidia-lightspeed-studios",
    "thq-nordic",
    "nintendo",
    "bioware",
    "capcom-usa-inc",
    "cd-projekt-red",
    "raven-software",
    "crystal-dynamics",
    "rockstar-north",
    "505-games",
    "digital-extremes",
    "team17-digital",
    "naughty-dog",
    "2k-australia",
    "codemasters",
    "fromsoftware",
    "deep-silver",
    "firaxis",
    "io-interactive-2",
    "ea-dice",
    "rockstar-games",
    "travellers-tales",
    "double-fine-productions",
    "volition",
    "relic-entertainment",
    "lucasarts-entertainment",
    "arkane-studios",
    "obsidian-entertainment",
    "plug-in-digital",
    "daedalic-entertainment",
    "remedy-entertainment",
    "eidos-montreal",
    "treyarch",
    "techland",
    "avalanche-studios",
    "bandai-namco-entertainment",
    "panic-button",
    "lucasfilm",
    "ubisoft-toronto",
    "turtle-rock-studios",
    "activision",
    "croteam",
    "rocksteady-studios",
    "dontnod-entertainment",
    "monolith-productions",
    "creative-assembly",
    "ubisoft-montpellier",
    "insomniac-games",
    "infinity-ward",
    "2k-marin",
    "irrational-games",
]

PUBLISHER_SLUGS: list[str] = [
    "electronic-arts",
    "square-enix",
    "ubisoft-entertainment",
    "microsoft-studios",
    "sega-2",
    "valve",
    "2k-games",
    "bethesda-softworks",
    "feral-interactive",
    "capcom",
    "warner-bros-interactive",
    "sony-computer-entertainment",
    "thq-nordic",
    "devolver-digital",
    "aspyr",
    "bandai-namco-entertainment",
    "activision-blizzard",
    "deep-silver",
    "nintendo",
    "sony-interactive-entertainment",
    "rockstar-games",
    "505-games",
    "paradox-interactive",
    "thq",
    "activison",
    "telltale-games",
    "team17-digital-ltd",
    "konami",
    "disney-interactive",
    "bandai-namco-entertainment-us",
    "1c-softclub",
    "focus-home-interactive",
    "1c-company",
    "lucasarts-entertainment",
    "codemasters",
    "daedalic-entertainment",
    "plug-in-digital-2",
    "cd-projekt-red",
    "eidos-interactive",
    "kiss-ltd",
]

GENRE_SLUGS: list[str] = [
    "action",
    "indie",
    "adventure",
    "role-playing-games-rpg",
    "strategy",
    "shooter",
    "casual",
    "simulation",
    "puzzle",
    "arcade",
    "platformer",
    "massively-multiplayer",
    "racing",
    "sports",
    "fighting",
    "family",
    "board-games",
    "card",
    "educational",
]

TAG_SLUGS: list[str] = [
    "singleplayer",
    "steam-achievements",
    "multiplayer",
    "full-controller-support",
    "steam-cloud",
    "steam-trading-cards",
    "great-soundtrack",
    "rpg",
    "co-op",
    "story-rich",
    "open-world",
    "cooperative",
    "first-person",
    "2d",
    "third-person",
    "sci-fi",
    "partial-controller-support",
    "horror",
    "fps",
    "online-co-op",
    "fantasy",
    "funny",
    "gore",
    "exploration",
    "difficult",
    "steam-leaderboards",
    "classic",
    "sandbox",
    "female-protagonist",
    "survival",
    "comedy",
    "violent",
    "free-to-play",
    "online-multiplayer",
    "stealth",
    "split-screen",
    "local-co-op",
    "action-adventure",
    "pixel-graphics",
    "action-rpg",
    "controller",
    "tactical",
    "local-multiplayer",
    "third-person-shooter",
    "early-access",
    "stats",
    "dark",
    "retro",
    "steam-workshop",
    "pvp",
    "anime",
    "cross-platform-multiplayer",
    "space",
    "zombies",
    "role-playing",
    "point-click",
    "includes-level-editor",
    "nudity",
    "moddable",
    "hack-and-slash",
    "war",
    "in-app-purchases",
    "character-customization",
    "family-friendly",
    "exclusive",
    "survival-horror",
    "turn-based",
    "post-apocalyptic",
    "cute",
]

ORDERINGS = [
    "name",
    "released",
    "added",
    "created",
    "updated",
    "rating",
    "metacritic",
    "-name",
    "-released",
    "-added",
    "-created",
    "-updated",
    "-rating",
    "-metacritic",
]